# -*- coding: utf-8 -*-
"""RealtimeFraudDetection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txPn0q53_GQtS0AmNY5xCV8aUd737vDj
"""

# REAL-TIME FRAUD DETECTION SYSTEM
!pip install imbalanced-learn shap --quiet


import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score

from imblearn.over_sampling import SMOTE
import shap


# Simulate REALISTIC Data

np.random.seed(42)
n_samples = 10000

data = pd.DataFrame({
    'amount': np.random.gamma(2, 100, n_samples),
    'time_of_day': np.random.randint(0, 24, n_samples),
    'device_score': np.random.rand(n_samples),
    'balance_after': np.random.normal(5000, 1500, n_samples),
})

# Add REAL pattern
data['is_fraud'] = (
    (data['amount'] > 300) &
    (data['device_score'] < 0.3) &
    (data['time_of_day'] > 20)
).astype(int)

# Train-Test Split

X = data.drop('is_fraud', axis=1)
y = data['is_fraud']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, test_size=0.2, random_state=42
)


# Handle Imbalance (SMOTE)

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)


# Scaling

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_res)
X_test_scaled = scaler.transform(X_test)


#  Random Forest

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_scaled, y_res)

y_pred_rf = rf.predict(X_test_scaled)
y_prob_rf = rf.predict_proba(X_test_scaled)[:, 1]

print("\n🔸 Random Forest Results:")
print(classification_report(y_test, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_rf))


#  Isolation Forest

iso = IsolationForest(contamination=0.05, random_state=42)
iso.fit(X_train_scaled)

y_pred_iso = iso.predict(X_test_scaled)
y_pred_iso = np.where(y_pred_iso == -1, 1, 0)

print("\n Isolation Forest Results:")
print(classification_report(y_test, y_pred_iso))


#  SHAP (FIXED PROPERLY)

print("\n SHAP Explainability")

explainer = shap.TreeExplainer(rf)

# NEW SAFE METHOD (no error)
shap_values = explainer(X_test_scaled[:100])

shap.summary_plot(
    shap_values.values,
    X_test_scaled[:100],
    feature_names=X.columns
)

#  Real-Time Prediction (IMPROVED)

def real_time_predict(new_transaction):
    scaled = scaler.transform([new_transaction])

    rf_prob = rf.predict_proba(scaled)[0][1]
    iso_score = iso.decision_function(scaled)[0]

    final_score = 0.7 * rf_prob + 0.3 * (-iso_score)

    return {
        "Fraud Probability": round(rf_prob, 4),
        "Anomaly Score": round(iso_score, 4),
        "Final Risk Score": round(final_score, 4)
    }


# Example Prediction

print("\n Real-time Prediction Example:")
new_txn = [400, 22, 0.2, 4500]  # should likely be fraud
print(real_time_predict(new_txn))